
server:
  port: 8083

spring:
  application:
    name: RATING-SERVICES
    
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka
      